'use strict';
const {app,BrowserWindow,ipcMain,session}=require('electron'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const PROJECT=process.env.MATERIALS_PROJECT,ROOT=__dirname,RESULTS=path.join(ROOT,'results');fs.mkdirSync(RESULTS,{recursive:true});app.setPath('userData',fs.mkdtempSync(path.join(RESULTS,'preview-profile-')));
const report={checks:[],electron:process.versions.electron},pending=[];let materials,chat;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const status={state:'active',id:'preview-session',generation:1,expiresAt:Date.now()+90000,persistence:'memory-only',documents:[{id:'d1',name:'Safety.pptx',state:'ready',pages:3,bytes:100,coverage:{textPages:3}}],busy:false};
const js=(w,s)=>w.webContents.executeJavaScript(s,true),marker=()=>({sessionId:status.id,generation:status.generation,expiresAt:status.expiresAt});
const respond=(job,text)=>job.resolve({success:true,preview:{page:job.page,kind:'slide',text}});
async function wait(fn,reason){for(let n=0;n<100;n++){if(await fn())return;await sleep(20)}throw Error(reason)}
function event(sources,mark=marker()){chat.webContents.send('transcription-llm-response',{response:'QA citation response',materialSession:mark,metadata:{materialSession:mark,sources}})}
const source=page=>({id:'source'+page,documentId:'d1',name:'Safety.pptx',kind:'slide',page});
app.whenReady().then(async()=>{try{session.defaultSession.webRequest.onBeforeRequest((d,cb)=>cb({cancel:/^https?:/.test(d.url)}));ipcMain.handle('materials-status',()=>({success:true,status}));ipcMain.handle('materials-preview',(_e,id,page)=>new Promise(resolve=>pending.push({id,page,resolve})));for(const [name,value] of [['get-speech-availability',false],['get-settings',{}],['get-exam-mode-state',{}],['get-window-stats',{}],['get-capture-mode',{}],['get-window-binding-status',{}],['get-shortcut-status',{}]])ipcMain.handle(name,()=>value);const options={show:true,width:820,height:740,webPreferences:{preload:path.join(PROJECT,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}};
 materials=new BrowserWindow(options);await materials.loadFile(path.join(PROJECT,'materials.html'));await sleep(100);await js(materials,"[...document.querySelectorAll('button')].find(b=>b.textContent==='Preview').click()");await wait(()=>pending.length===1,'initial preview not requested');respond(pending.shift(),'FIRST_PAGE');await wait(()=>js(materials,"document.getElementById('preview').open"),'initial dialog did not open');
 await js(materials,"document.getElementById('page').value=2;document.getElementById('open-page').click()");await wait(()=>pending.length===1,'second page not requested');await js(materials,"document.getElementById('preview-close').click()");await sleep(30);respond(pending.shift(),'LATE_CLOSED_PAGE');await sleep(80);assert.equal(await js(materials,"document.getElementById('preview').open"),false);assert.doesNotMatch(await js(materials,'document.body.innerText'),/LATE_CLOSED_PAGE/);report.checks.push('closed material preview cannot reopen from delayed page result');
 await js(materials,"[...document.querySelectorAll('button')].find(b=>b.textContent==='Preview').click()");await wait(()=>pending.length===1,'reopen missing');respond(pending.shift(),'FIRST_PAGE');await sleep(30);await js(materials,"document.getElementById('page').value=2;document.getElementById('open-page').click();document.getElementById('page').value=3;document.getElementById('open-page').click()");await wait(()=>pending.length===2,'competing page requests missing');const page2=pending.shift(),page3=pending.shift();assert.equal(page2.page,2);assert.equal(page3.page,3);respond(page3,'CURRENT_PAGE_THREE');await sleep(50);respond(page2,'STALE_PAGE_TWO');await sleep(80);assert.match(await js(materials,"document.getElementById('preview-text').textContent"),/CURRENT_PAGE_THREE/);assert.doesNotMatch(await js(materials,'document.body.innerText'),/STALE_PAGE_TWO/);report.checks.push('newer material page request wins over older reply');
 chat=new BrowserWindow(options);await chat.loadFile(path.join(PROJECT,'chat.html'));await sleep(100);event([source(1),source(2)]);await wait(()=>js(chat,"[...document.querySelectorAll('section button')].filter(b=>b.textContent.includes('Safety.pptx')).length===2"),'citation buttons missing');await js(chat,"[...document.querySelectorAll('section button')].filter(b=>b.textContent.includes('Safety.pptx')).forEach(b=>b.click())");await wait(()=>pending.length===2,'citation requests missing');const a=pending.shift(),b=pending.shift();respond(b,'CURRENT_CITATION_TWO');await sleep(50);respond(a,'OLD_CITATION_ONE');await sleep(70);assert.match(await js(chat,'document.body.innerText'),/CURRENT_CITATION_TWO/);assert.doesNotMatch(await js(chat,'document.body.innerText'),/OLD_CITATION_ONE/);report.checks.push('newer citation request wins over older reply');
 await js(chat,"[...document.querySelectorAll('button')].find(b=>b.textContent==='Close source preview').click()");chat.webContents.send('materials-session-invalidated',{reason:'removed'});status.generation=2;chat.webContents.send('materials-status-changed',status);await sleep(50);event([source(1)],{...marker(),generation:1});await sleep(50);assert.equal(await js(chat,"[...document.querySelectorAll('section button')].filter(b=>b.textContent.includes('Safety.pptx')).length"),0);report.checks.push('stale-generation source event cannot restore removed citations');
 status.expiresAt=Date.now()+180;chat.webContents.send('materials-status-changed',status);event([source(2)]);await wait(()=>js(chat,"[...document.querySelectorAll('section button')].some(b=>b.textContent.includes('Safety.pptx'))"),'fresh short-lived source missing');await sleep(250);assert.equal(await js(chat,"[...document.querySelectorAll('section button')].filter(b=>b.textContent.includes('Safety.pptx')).length"),0);assert.equal(await js(chat,"[...document.querySelectorAll('dialog')].some(d=>d.open)"),false);report.checks.push('source citation timer self-clears at deadline without another status IPC');
 fs.writeFileSync(path.join(RESULTS,'preview-current.png'),await(await materials.webContents.capturePage()).toPNG());report.success=true;
 }catch(error){report.success=false;report.error=error.stack}finally{materials?.destroy();chat?.destroy();fs.writeFileSync(path.join(RESULTS,'native-preview.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));app.exit(report.success?0:1)}});
