'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),path=require('node:path');
const {PROJECT,fixture}=require('../supplemental-v1/helpers.cjs');
const {createProvider}=require(path.join(PROJECT,'server/providers')),{createMaterialsDirectAnswer}=require(path.join(PROJECT,'src/services/materials-direct-answer')),{attachMaterialsSession}=require(path.join(PROJECT,'src/services/materials-routing'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const ctx=()=>({sessionId:'qa-eof-session',generation:1,expiresAt:Date.now()+600,sources:[{id:'s1',documentId:'d1',name:'Safety.pdf',page:1,kind:'page',text:'EOF material fixture'}]});
async function upstream(t){let calls=0;const server=http.createServer(async(req,res)=>{calls++;for await(const chunk of req){}res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('data: {"choices":[{"delta":{"content":"early answer"}}]}\n\ndata: [DONE]\n\n');await sleep(750);res.end()});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.close(r);server.closeAllConnections()}));return {url:`http://127.0.0.1:${server.address().port}`,get calls(){return calls}}}
for(const boundary of ['shared provider','direct answer'])test(`${boundary}: terminal frame before expiry plus EOF after expiry cannot return success`,async t=>{const f=await upstream(t),materialContext=ctx(),deltas=[],payload={provider:'deepseek',text:'question',history:[],skill:'general',materialContext},signal=new AbortController().signal;const fn=boundary==='shared provider'?createProvider({deepseekKey:'qa-only',deepseekModel:'qa',limits:{outputTokens:20}},{deepseek:f.url}):createMaterialsDirectAnswer({llmService:{isInitialized:true,provider:'deepseek',model:'qa',deepseekClient:{apiKey:'qa-only',model:'qa',baseUrl:f.url}}});await assert.rejects(()=>fn(payload,{signal,onDelta:d=>deltas.push(d)}));assert.deepEqual(deltas,['early answer']);assert.equal(f.calls,1)});
for(const withMaterial of [false,true])test(`shared provider rejects DeepSeek image before HTTP (${withMaterial?'material':'ordinary'} input)`,async t=>{const f=await upstream(t),provider=createProvider({deepseekKey:'qa-only',limits:{outputTokens:20}},{deepseek:f.url});await assert.rejects(()=>provider({provider:'deepseek',text:'image?',history:[],skill:'general',image:{mimeType:'image/png',data:'AAAA'},...(withMaterial?{materialContext:ctx()}:{})},{signal:new AbortController().signal,onDelta(){}}));assert.equal(f.calls,0)});
for(const mode of ['direct','managed'])test(`active ${mode} DeepSeek screenshot rejects before either provider dispatch`,async t=>{const f=await fixture(t),old=process.env.LLM_PROVIDER;process.env.LLM_PROVIDER='deepseek';t.after(()=>{if(old===undefined)delete process.env.LLM_PROVIDER;else process.env.LLM_PROVIDER=old});let calls=0;const service={};for(const name of ['processTextWithSkill','processTextWithSkillStream','processTranscriptionWithIntelligentResponse','processTranscriptionWithIntelligentResponseStream','processImageWithSkill','processImageWithSkillStream'])service[name]=async()=>{calls++;return {response:'wrong legacy call'}};const answer=async()=>{calls++;return {text:'wrong provider call'}};attachMaterialsSession(service,{materials:f.m,getAIMode:()=>mode,managedSession:{answerScoped:answer},answerDirect:answer});await assert.rejects(()=>service.processImageWithSkillStream(Buffer.from('fixture'),'image/png','general',[],null,()=>{}));assert.equal(calls,0)});
