'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const PROJECT=process.env.MATERIALS_PROJECT||'/mnt/c/users/endeg/Desktop/NoCatch-session-materials';
const {createManagedServer}=require(path.join(PROJECT,'server/app')),{readConfig}=require(path.join(PROJECT,'server/auth'));
const ROOT=path.join(__dirname,'results','temporary');fs.mkdirSync(ROOT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function setup(t,provider){const dir=fs.mkdtempSync(path.join(ROOT,'backend-'));const config={...readConfig({OIDC_ISSUER:'https://issuer.example/',OIDC_AUDIENCE:'desktop-api',OIDC_JWKS_URL:'https://issuer.example/keys',GEMINI_API_KEY:'test-only',DEEPSEEK_API_KEY:'test-only'}),database:path.join(dir,'requests.sqlite')};const app=createManagedServer({config,authenticate:async req=>{const owner=req.headers.authorization?.replace('Bearer ','');if(!owner)throw Object.assign(Error('unauthorized'),{status:401,code:'unauthorized'});return {subject:owner.split(':')[0],account:owner.split(':')[0],owner,expiresAt:Date.now()+60000}},provider:provider|| (async(input,{onDelta})=>onDelta('DERIVED_SECRET_OUTPUT_813 '+input.materialContext?.sources[0].text))});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${app.server.address().port}`;t.after(async()=>{await app.close();fs.rmSync(dir,{recursive:true,force:true})});const request=(route,{method='GET',owner='alice:session',body,key}={})=>fetch(base+route,{method,headers:{Authorization:`Bearer ${owner}`,...(body?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});const context=(expiresAt=Date.now()+60000)=>({sessionId:randomUUID(),generation:1,expiresAt,sources:[{id:'source-1',documentId:'document-1',name:'PRIVATE_DECK_572.pptx',page:2,kind:'slide',text:'MATERIAL_SECRET_TEXT_913 safety reserve is 718 liters.'}]});const register=(ctx,owner)=>request('/v1/material-sessions',{method:'POST',owner,body:{sessionId:ctx.sessionId,expiresAt:ctx.expiresAt}});const submit=(ctx,options={})=>request('/v1/answers',{method:'POST',key:randomUUID(),body:{provider:'gemini',text:'What is the reserve?',materialContext:ctx},...options});return {app,dir,request,context,register,submit};}
async function done(f,id){for(let n=0;n<100;n++){const r=await f.request(`/v1/requests/${id}`);if(r.status!==200)return {http:r.status};const row=await r.json();if(row.status!=='accepted')return row;await sleep(10)}throw Error('answer did not finish')}
function noDiskContent(dir){for(const name of fs.readdirSync(dir)){const p=path.join(dir,name);if(fs.statSync(p).isFile()){const b=fs.readFileSync(p);for(const secret of ['DERIVED_SECRET_OUTPUT_813','MATERIAL_SECRET_TEXT_913','PRIVATE_DECK_572.pptx'])assert.equal(b.includes(Buffer.from(secret)),false,`${secret} leaked to ${name}`)}}}
test('registered material context reaches provider and output/events never reach plaintext durable store',async t=>{let input;const f=await setup(t,async(i,{onDelta})=>{input=i;onDelta('DERIVED_SECRET_OUTPUT_813 '+i.materialContext?.sources[0].text)}),ctx=f.context();assert.ok((await f.register(ctx)).ok);const r=await f.submit(ctx);assert.equal(r.status,202);const {id}=await r.json(),row=await done(f,id);assert.equal(row.status,'completed');assert.match(row.text,/DERIVED_SECRET_OUTPUT_813/);assert.deepEqual(input.materialContext,ctx);assert.equal(input.text,'What is the reserve?');noDiskContent(f.dir);const ev=await (await f.request(`/v1/requests/${id}/events`)).text();assert.match(ev,/DERIVED_SECRET_OUTPUT_813/);noDiskContent(f.dir);});
test('unregistered, expired, cross-owner and mismatched-deadline contexts reject before provider dispatch',async t=>{let calls=0;const f=await setup(t,async(i,{onDelta})=>{calls++;onDelta('unexpected')});let ctx=f.context();assert.ok((await f.submit(ctx)).status>=400);assert.ok((await f.register(ctx)).ok);assert.ok((await f.submit(ctx,{owner:'bob:session'})).status>=400);assert.ok((await f.submit({...ctx,expiresAt:ctx.expiresAt+1})).status>=400);assert.ok((await f.submit({...ctx,expiresAt:Date.now()-1})).status>=400);assert.equal(calls,0);});
test('material registration cannot extend deadline or cross account ownership',async t=>{const f=await setup(t),ctx=f.context();assert.ok((await f.register(ctx)).ok);const again=await f.register({...ctx,expiresAt:ctx.expiresAt+30000});if(again.ok)assert.equal((await again.json()).expiresAt,ctx.expiresAt);else assert.ok(again.status>=400);assert.ok((await f.register(ctx,'bob:session')).status>=400);const far=f.context(Date.now()+91*60000);const r=await f.register(far);if(r.ok)assert.ok((await r.json()).expiresAt<=Date.now()+90*60000);else assert.ok(r.status>=400);});
test('delete makes material output and SSE replay unavailable and old context cannot redispatch',async t=>{const f=await setup(t),ctx=f.context();assert.ok((await f.register(ctx)).ok);const r=await f.submit(ctx);assert.equal(r.status,202);const {id}=await r.json();await done(f,id);assert.ok((await f.request(`/v1/material-sessions/${ctx.sessionId}`,{method:'DELETE'})).ok);for(const tail of ['','/events']){const res=await f.request(`/v1/requests/${id}${tail}`);assert.ok(res.status>=400);assert.doesNotMatch(await res.text(),/DERIVED_SECRET_OUTPUT_813|MATERIAL_SECRET_TEXT_913/)}assert.ok((await f.submit(ctx)).status>=400);noDiskContent(f.dir);});
test('deadline aborts pending material provider and suppresses late deltas/final/replay',async t=>{let release,aborted=false;const f=await setup(t,async(i,{signal,onDelta})=>{onDelta('DERIVED_SECRET_OUTPUT_813 partial');await new Promise(r=>{release=r;signal.addEventListener('abort',()=>{aborted=true;r()},{once:true})});onDelta('LATE_AFTER_EXPIRY')});const ctx=f.context(Date.now()+250);assert.ok((await f.register(ctx)).ok);const response=await f.submit(ctx);assert.equal(response.status,202);const {id}=await response.json();await sleep(350);release?.();await sleep(30);const r=await f.request(`/v1/requests/${id}`);assert.ok(r.status>=400);assert.doesNotMatch(await r.text(),/LATE_AFTER_EXPIRY|DERIVED_SECRET_OUTPUT_813/);assert.ok(aborted,'pending provider aborted at material deadline');noDiskContent(f.dir);});
test('backend includes material in total prompt budget and rejects malformed source coordinates',async t=>{let calls=0;const f=await setup(t,async(i,{onDelta})=>{calls++;onDelta('unexpected')});const ctx=f.context();assert.ok((await f.register(ctx)).ok);for(const malformed of [{...ctx,sources:[{...ctx.sources[0],page:0}]},{...ctx,sources:[{...ctx.sources[0],text:'x'.repeat(40000)}]},{...ctx,generation:-1}])assert.ok((await f.submit(malformed)).status>=400);assert.equal(calls,0);});
