'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const PROJECT=process.env.MATERIALS_PROJECT||'/mnt/c/users/endeg/Desktop/NoCatch-session-materials';
const {MaterialsManager,LIMITS}=require(path.join(PROJECT,'src/materials'));
const ROOT=__dirname,FIX=path.join(ROOT,'fixtures'),RUN=path.join(ROOT,'results','temporary');fs.mkdirSync(RUN,{recursive:true});
const fixture=n=>path.join(FIX,n),DAY=Date.UTC(2026,8,29,12);
function secureStorage(){const key=crypto.createHash('sha256').update('QA OS key boundary stand-in').digest();let decrypts=0;return {isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=> 'gnome_libsecret',encryptString(s){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(s,'utf8'),c.final(),c.getAuthTag()]);},decryptString(b){decrypts++;const d=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));d.setAuthTag(b.subarray(-16));return Buffer.concat([d.update(b.subarray(12,-16)),d.final()]).toString();},get decrypts(){return decrypts}};}
function setup(t,options={}){let clock=DAY;const dir=fs.mkdtempSync(path.join(RUN,'store-')),safeStorage=options.safeStorage||secureStorage(),invalidations=[];const config={userDataPath:dir,safeStorage,owner:'qa-alice',now:()=>clock,onInvalidate:(...a)=>invalidations.push(a),...options};let m=new MaterialsManager(config);const managers=[m];t.after(async()=>{for(const obj of managers)await obj.close();fs.rmSync(dir,{recursive:true,force:true});});return {m,dir,safeStorage,invalidations,setTime:v=>clock=v,advance:v=>clock+=v,reopen:()=>{const n=new MaterialsManager(config);managers.push(n);return n}};}
const ready=s=>(s.documents||[]).filter(d=>!d.error&&!['failed','error','extracting','pending','importing'].includes(d.state));
const sources=m=>m.retrieve('Zephyr Xenon Quasar Aurora launch reserve calibration safety')?.sources||[];
async function inaccessible(fn){try{const v=await fn();assert.ok(!v||v.error||!(v.sources?.length||v.text||v.notes),'expired/unauthorized content returned')}catch(e){if(e.code==='ERR_ASSERTION')throw e;}}
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(path.join(dir,x.name)):[path.join(dir,x.name)]);}
function diskLeaks(dir,needles){for(const p of files(dir)){const b=fs.readFileSync(p);for(const n of needles)assert.equal(b.includes(Buffer.from(n)),false,`plaintext ${n} in ${p}`);}}
const ppt='relationship-order-notes-visual.pptx';
test('public module exports manager and declared limits',()=>{assert.equal(typeof MaterialsManager,'function');assert.equal(typeof LIMITS,'object');});
test('real PPTX follows presentation relationships and preserves table/notes with honest visual gaps',async t=>{const {m}=setup(t);await m.importFiles([fixture(ppt)]);const [d]=ready(m.status());assert.ok(d,'PPTX accepted');assert.equal(d.pages,3);const p1=await m.preview(d.id,1),p2=await m.preview(d.id,2),p3=await m.preview(d.id,3);assert.equal(p1.page,1);assert.match(JSON.stringify(p1),/MARIGOLD-629/);assert.doesNotMatch(JSON.stringify(p1),/PHYSICAL ONE/);assert.match(JSON.stringify(p1),/FIRST_SLIDE_NOTE/);assert.match(JSON.stringify(p2),/17 minutes/);assert.match(JSON.stringify(p2),/318 liters/);assert.match(JSON.stringify(p2),/PRIVATE_NOTES_SENTINEL/);assert.ok(d.coverage,'coverage must be reported');assert.match(JSON.stringify([d.coverage,p3.coverage]),/partial|visual|image|unsupported|unavailable|missing|gap|empty/i);});
test('real PDF preserves text/page boundaries and exposes image-only coverage',async t=>{const {m}=setup(t);await m.importFiles([fixture('three-pages.pdf')]);const [d]=ready(m.status());assert.ok(d);assert.equal(d.pages,3);assert.match(JSON.stringify(await m.preview(d.id,1)),/PDF_ONE_SENTINEL/);assert.doesNotMatch(JSON.stringify(await m.preview(d.id,1)),/PDF_TWO_SENTINEL/);assert.match(JSON.stringify(await m.preview(d.id,2)),/PDF_TWO_SENTINEL/);assert.match(JSON.stringify([d.coverage,(await m.preview(d.id,3)).coverage]),/partial|visual|image|unsupported|unavailable|missing|gap|empty/i);});
test('preparation is local, explicit consent required, active start cannot move the 90-minute deadline',async t=>{const f=setup(t),{m}=f;await m.importFiles([fixture(ppt)]);assert.equal(sources(m).length,0);await assert.rejects(async()=>m.start({consent:false}));assert.equal(sources(m).length,0);await m.start({consent:true});const first=m.status(),ctx=m.retrieve('Zephyr launch code');assert.equal(first.expiresAt,DAY+90*60000);assert.ok(ctx.sources.length);assert.equal(ctx.sessionId,first.id);assert.equal(ctx.generation,first.generation);assert.equal(ctx.expiresAt,first.expiresAt);assert.ok(ctx.sources.some(s=>s.page===1&&/MARIGOLD-629/.test(s.text)));f.advance(1000);await m.start({consent:true});assert.equal(m.status().expiresAt,first.expiresAt);});
test('content deduplication survives renamed copy; failures are visible and free capacity',async t=>{const {m,dir}=setup(t);const copy=path.join(dir,'renamed.pptx');fs.copyFileSync(fixture(ppt),copy);await m.importFiles([fixture(ppt),copy,fixture('corrupt.pptx'),fixture('corrupt.pdf'),fixture('legacy.ppt')]);assert.equal(ready(m.status()).length,1);assert.ok(m.status().documents.filter(d=>d.error||['failed','error'].includes(d.state)).length>=3,'individual failures visible');await m.importFiles([fixture('unique-1.pdf')]);assert.equal(ready(m.status()).length,2);});
test('ten accepted documents cap; remove frees capacity',async t=>{const {m}=setup(t);await m.importFiles(Array.from({length:11},(_,i)=>fixture(`unique-${i+1}.pdf`)));assert.equal(ready(m.status()).length,10);const removed=ready(m.status())[0];await m.remove(removed.id);assert.equal(ready(m.status()).length,9);await m.importFiles([fixture('unique-11.pdf')]);assert.equal(ready(m.status()).length,10);await inaccessible(()=>m.preview(removed.id,1));});
test('251-page PDF and >4MiB inflated text fail before becoming accepted documents',async t=>{const {m}=setup(t);await m.importFiles([fixture('251-pages.pdf'),fixture('inflated-text.pptx')]);assert.equal(ready(m.status()).length,0);assert.ok(m.status().documents.filter(d=>d.error||['failed','error'].includes(d.state)).length>=2);});
test('file over 50MiB rejected and does not consume capacity',async t=>{const {m,dir}=setup(t);const large=path.join(dir,'too-large.pdf'),fd=fs.openSync(large,'w');fs.ftruncateSync(fd,50*1024*1024+1);fs.closeSync(fd);await m.importFiles([large,fixture('unique-1.pdf')]);assert.equal(ready(m.status()).length,1);assert.ok(m.status().documents.some(d=>d.error));});
test('deadline boundary rejects sources/preview and invalidates snapshot exactly at expiry',async t=>{const f=setup(t),{m}=f;await m.importFiles([fixture(ppt)]);await m.start({consent:true});const snap=m.snapshot(),d=ready(m.status())[0],deadline=m.status().expiresAt;f.setTime(deadline-1);assert.ok(m.isCurrent(snap));assert.ok(sources(m).length);f.setTime(deadline);assert.equal(m.isCurrent(snap),false);assert.equal(sources(m).length,0);await inaccessible(()=>m.preview(d.id,1));assert.ok(f.invalidations.length);});
test('same-owner encrypted recovery retains original deadline and no plaintext text/names/notes on disk',async t=>{const f=setup(t),{m}=f;await m.importFiles([fixture(ppt)]);await m.start({consent:true});const expiry=m.status().expiresAt;assert.equal(m.status().persistence,'encrypted');assert.ok(files(f.dir).length,'durable encrypted recovery exists');diskLeaks(f.dir,[ppt,'MARIGOLD-629','PRIVATE_NOTES_SENTINEL','318 liters']);await m.close();f.advance(60000);const r=f.reopen();await r.restore();assert.equal(r.status().expiresAt,expiry);assert.ok(sources(r).length);});
test('startup expires before unwrapping OS key',async t=>{const f=setup(t),{m}=f;await m.importFiles([fixture(ppt)]);await m.start({consent:true});const expiry=m.status().expiresAt;await m.close();const before=f.safeStorage.decrypts;f.setTime(expiry);const r=f.reopen();await r.restore();assert.equal(f.safeStorage.decrypts,before,'expired startup must not decrypt');assert.equal(sources(r).length,0);assert.equal(ready(r.status()).length,0);});
test('draft recovery cannot renew the original 30-minute preparation lifetime',async t=>{const f=setup(t),{m}=f;await m.importFiles([fixture(ppt)]);const d=ready(m.status())[0];await m.close();f.advance(29*60000);const r=f.reopen();await r.restore();assert.equal(ready(r.status()).length,1);f.advance(60000);await inaccessible(()=>r.preview(d.id,1));await assert.rejects(async()=>r.start({consent:true}));assert.equal(sources(r).length,0);});
for(const backend of ['basic_text','unavailable'])test(`${backend} safeStorage reports memory-only and persists no material`,async t=>{const safeStorage={isEncryptionAvailable:()=>backend!=='unavailable',getSelectedStorageBackend:()=>backend,encryptString(){throw Error('weak storage must never encrypt')},decryptString(){throw Error('weak storage must never decrypt')}};const f=setup(t,{safeStorage}),{m}=f;await m.importFiles([fixture(ppt)]);await m.start({consent:true});assert.match(m.status().persistence,/memory|session.only/);diskLeaks(f.dir,[ppt,'MARIGOLD-629','PRIVATE_NOTES_SENTINEL']);await m.close();const r=f.reopen();await r.restore();assert.equal(ready(r.status()).length,0);});
test('owner change invalidates snapshots synchronously and cannot restore prior owner content',async t=>{const f=setup(t),{m}=f;await m.importFiles([fixture(ppt)]);await m.start({consent:true});const snap=m.snapshot();const pending=m.setOwner('qa-bob');assert.equal(m.isCurrent(snap),false);assert.equal(sources(m).length,0);await pending;await m.close();const r=f.reopen();await r.restore();assert.equal(sources(r).length,0);assert.equal(ready(r.status()).length,0);});
test('remove/end invalidate snapshots and erase source access',async t=>{const {m}=setup(t);await m.importFiles([fixture(ppt),fixture('three-pages.pdf')]);await m.start({consent:true});let snap=m.snapshot();const d=ready(m.status()).find(d=>d.name===ppt);await m.remove(d.id);assert.equal(m.isCurrent(snap),false);assert.ok(!sources(m).some(s=>s.documentId===d.id));await inaccessible(()=>m.preview(d.id,1));snap=m.snapshot();await m.end('qa-finished');assert.equal(m.isCurrent(snap),false);assert.equal(sources(m).length,0);assert.equal(ready(m.status()).length,0);});
test('retrieval honors explicit text budget and exposes bounded genuine source coordinates',async t=>{const {m}=setup(t);await m.importFiles([fixture(ppt),fixture('three-pages.pdf')]);await m.start({consent:true});const ctx=m.retrieve('Zephyr Xenon Quasar Aurora',{maxChars:180});assert.ok(ctx.sources.length);assert.ok(ctx.sources.reduce((n,s)=>n+s.text.length,0)<=180);for(const s of ctx.sources){assert.equal(typeof s.id,'string');assert.equal(typeof s.documentId,'string');assert.ok(s.name);assert.ok(Number.isInteger(s.page)&&s.page>=1);assert.ok(s.kind);assert.equal(typeof s.text,'string');}});
function deferred(){let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)}}
for(const action of ['cancelImports','setOwner','end'])test(`pending extraction cannot commit after ${action}; start rejects pending work`,async t=>{const gate=deferred(),began=deferred();const f=setup(t,{extractor:async()=>{began.resolve();await gate.promise;return {pages:[{page:1,kind:'page',text:'LATE_COMMIT_SENTINEL'}],coverage:{totalPages:1,textPages:1,visualPages:0}}}}),{m}=f;const importing=m.importFiles([fixture('unique-1.pdf')]);await began.promise;assert.ok(m.status().busy);await assert.rejects(async()=>m.start({consent:true}));const snap=m.snapshot();const op=action==='setOwner'?m.setOwner('qa-bob'):action==='end'?m.end('qa'):m.cancelImports();assert.equal(m.isCurrent(snap),false);gate.resolve();await op;await importing.catch(()=>{});assert.equal(ready(m.status()).length,0);assert.equal(sources(m).length,0);});
test('same generation cannot commit extraction at original draft deadline',async t=>{const gate=deferred(),began=deferred();const f=setup(t,{extractor:async()=>{began.resolve();await gate.promise;return {pages:[{page:1,kind:'page',text:'EXPIRED_COMMIT_SENTINEL'}],coverage:{totalPages:1,textPages:1,visualPages:0}}}}),{m}=f;const importing=m.importFiles([fixture('unique-1.pdf')]);await began.promise;f.advance(30*60000);gate.resolve();await importing.catch(()=>{});assert.equal(ready(m.status()).length,0);assert.equal(sources(m).length,0);});
