'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const ROOT=__dirname,PROJECT=path.resolve(ROOT,'../..'),command=process.argv[2]||'test',args=process.argv.slice(3),results=path.join(ROOT,'results');fs.mkdirSync(results,{recursive:true});
const arg=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:args[i+1]};
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function sourceHashes(){for(const [rel,record] of Object.entries(JSON.parse(fs.readFileSync(path.join(ROOT,'SOURCE-HASHES.json'),'utf8')).files))if(hash(path.join(ROOT,rel))!==record.sha256)throw Error('Frozen copied source changed: '+rel)}
function fixtureHashes(){const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'expected-fixtures.json'),'utf8'));for(const [name,record] of Object.entries(manifest.files))if(hash(path.join(ROOT,'fixtures',name))!==record.sha256)throw Error('Fixture differs from frozen expected bytes: '+name)}
function execute(binary,argv,extra={}){const env={...process.env,MATERIALS_PROJECT:PROJECT,...extra};if(command.startsWith('native-'))delete env.ELECTRON_RUN_AS_NODE;const r=spawnSync(binary,argv,{cwd:PROJECT,env,encoding:'utf8',maxBuffer:20*1024*1024});const label=command+'-'+new Date().toISOString().replace(/[:.]/g,'-');fs.writeFileSync(path.join(results,label+'.log'),(r.stdout||'')+(r.stderr||''));fs.writeFileSync(path.join(results,label+'.json'),JSON.stringify({binary,argv,project:env.MATERIALS_PROJECT,status:r.status,error:r.error?.message},null,2)+'\n');if(r.stdout)process.stdout.write(r.stdout);if(r.stderr)process.stderr.write(r.stderr);if(r.error)throw r.error;return r.status??1}
try{sourceHashes();let code=0;
if(command==='hashes'){fixtureHashes();console.log('Frozen source and fixture hashes match.')}
else if(command==='fixtures'){code=execute(arg('--python',process.platform==='win32'?'python':'python3'),[path.join(ROOT,'generate-fixtures.py')]);if(!code)fixtureHashes()}
else if(command==='test'){fixtureHashes();code=execute(process.execPath,['--test','--test-timeout=30000',...['materials-public.test.cjs','materials-context.test.cjs','materials-managed.test.cjs','supplemental-v1/routing.test.cjs','supplemental-v1/setup.test.cjs','supplemental-v1/main-boundary.test.cjs','supplemental-v1/managed-client.test.cjs','supplemental-v1/backend-restart.test.cjs'].map(n=>path.join(ROOT,n))])}
else if(command==='regression'){code=execute(process.execPath,['--test',...['test-managed-server.js','test-managed-client.js','test-main-session-isolation.cjs','test-onboarding.js','test-setup-service.js','test-packaging.js','test-managed-config-packaging.js'].map(n=>path.join(PROJECT,'scripts',n))])}
else if(command==='archive'){if(!args[0])throw Error('Provide path to app.asar');code=execute(process.execPath,[path.join(ROOT,'supplemental-v2/verify-archive.cjs'),path.resolve(args[0])])}
else if(command.startsWith('native-')){fixtureHashes();const scripts={'native-materials':'supplemental-v1/native-renderer.cjs','native-chat':'supplemental-v1/chat-v3/native-chat.cjs','native-main':'supplemental-v2/full-main.cjs'};if(!scripts[command])throw Error('Unknown native command');const binary=arg('--electron');if(!binary)throw Error('Provide --electron path to a standalone Electron binary, not the installed application executable.');const target=arg('--project',PROJECT);code=execute(path.resolve(binary),[path.join(ROOT,scripts[command])],{MATERIALS_PROJECT:path.resolve(target),MATERIALS_QA_PHASE:arg('--phase','first-run')})}
else throw Error('Choose fixtures, hashes, test, regression, archive, native-materials, native-chat, or native-main.');process.exitCode=code;
}catch(error){console.error(error.message);process.exitCode=1}
