'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {PROJECT,fixture,deferred,tick,invalidate}=require('./helpers.cjs');
async function harness(t){const f=await fixture(t),events=[],memory=[],panels=[],requests=[],logs=[];const capture=deferred();let blockCapture=false;
const provider=(...args)=>{const gate=deferred();requests.push({...gate,delta:args.at(-1)});return gate.promise};
const context={Buffer,console,setTimeout,clearTimeout,setInterval,clearInterval,AbortController,process:{env:{}},config:{get:()=> 'both'},logger:Object.fromEntries(['info','warn','debug','error'].map(k=>[k,(...args)=>logs.push(args)])),sessionManager:{addUserInput:text=>memory.push({role:'user',text}),addModelResponse:text=>memory.push({role:'model',text}),addConversationEvent:event=>memory.push(event),clear:()=>memory.length=0,getOptimizedHistory:()=>({recent:[]})},llmService:{processTextWithSkillStream:provider,processImageWithSkillStream:provider,processTranscriptionWithIntelligentResponseStream:provider,generateIntelligentFallbackResponse:()=>({response:'FALLBACK_BAD',metadata:{}})},captureService:{captureAndProcess:async()=>{if(blockCapture)await capture.promise;return {imageBuffer:Buffer.from('fixture-image'),mimeType:'image/png'}}},speechService:{cancelRecording(){}},windowManager:{broadcastToAllWindows:(channel,data)=>events.push({channel,data}),showWindow(){},showLLMLoading:()=>panels.push('loading'),showLLMResponse:text=>panels.push(text),hideLLMResponse:()=>panels.push('hidden')}};
const source=fs.readFileSync(path.join(PROJECT,'main.js'),'utf8'),start=source.indexOf('class ApplicationController {'),end=source.indexOf('const gotSingleInstanceLock');assert.ok(start>=0&&end>start);const C=vm.runInNewContext(source.slice(start,end)+'\nApplicationController',context),c=Object.create(C.prototype);Object.assign(c,{materialsManager:f.m,operationEpoch:0,activeSkill:'general',codingLanguage:null,isReady:true,setupService:{invalidate(){}},managedSession:{cancelAll:async()=>{},status:()=>({signingIn:false})},getAnswerSurface:()=> 'both',shouldShowAnswerPanel:()=>true,shouldShowVoiceOverlay:()=>true,sendToVoiceResponseWindows:(channel,data)=>events.push({channel,data}),sendTranscriptionLLMResponseToVoiceTargets:r=>events.push({channel:'voice-final',data:r}),broadcastTranscriptionLLMResponse:r=>events.push({channel:'text-final',data:r})});
return {...f,c,events,memory,panels,requests,logs,capture,setCaptureWait:()=>blockCapture=true,clearOutputs(){events.length=0;memory.length=0;panels.length=0;logs.length=0}}}
const invoke=(f,surface)=>surface==='text'?f.c.processWithLLM('Zephyr QUESTION_SECRET_943',{recent:[]}):surface==='voice'?f.c.processTranscriptionWithLLM('Zephyr QUESTION_SECRET_943',{recent:[]}):f.c.triggerScreenshotOCR();
const finish=r=>{r.delta('DELTA_SECRET_137');r.resolve({response:'ANSWER_SECRET_672',metadata:{sources:[{id:'source-qa',page:1}],processingTime:1,usedFallback:false}})};
for(const surface of ['text','voice','screenshot'])for(const action of ['owner','end','remove','expire'])for(const outcome of ['success','failure'])test(`real main ${surface}: ${action} suppresses late ${outcome}, history, panel and fallback`,async t=>{const f=await harness(t),pending=invoke(f,surface);await tick();assert.equal(f.requests.length,1);await invalidate(f,action);f.clearOutputs();if(outcome==='success')finish(f.requests[0]);else f.requests[0].reject(Error('LATE_PROVIDER_ERROR'));await pending;assert.deepEqual(f.events,[]);assert.deepEqual(f.memory,[]);assert.deepEqual(f.panels,[]);assert.doesNotMatch(JSON.stringify(f.logs),/LATE_PROVIDER_ERROR|ANSWER_SECRET|DELTA_SECRET/)});
for(const surface of ['text','voice','screenshot'])test(`real main ${surface}: current material answer displays without plaintext previews in logs`,async t=>{const f=await harness(t),pending=invoke(f,surface);await tick();finish(f.requests[0]);await pending;assert.ok(f.memory.some(e=>e.role==='model'&&e.text==='ANSWER_SECRET_672'));assert.ok(f.panels.includes('ANSWER_SECRET_672'));assert.doesNotMatch(JSON.stringify(f.logs),/QUESTION_SECRET_943|ANSWER_SECRET_672|DELTA_SECRET_137/)});
test('real main screenshot capture completing after expiry does not dispatch provider',async t=>{const f=await harness(t);f.setCaptureWait();const pending=invoke(f,'screenshot');await tick();f.expire();f.clearOutputs();f.capture.resolve();await tick();const dispatched=f.requests.length;if(dispatched)finish(f.requests[0]);await pending;assert.equal(dispatched,0);assert.deepEqual(f.events,[]);assert.deepEqual(f.memory,[])});
