'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {PROJECT,fixture,deferred,tick,invalidate}=require('./helpers.cjs');
const {attachMaterialsSession}=require(path.join(PROJECT,'src/services/materials-routing'));
const names=['processTextWithSkill','processTextWithSkillStream','processTranscriptionWithIntelligentResponse','processTranscriptionWithIntelligentResponseStream','processImageWithSkill','processImageWithSkillStream'];
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aB1sAAAAASUVORK5CYII=','base64');
function harness(m,{mode='direct',gate}={}){const legacy=[],calls=[],deltas=[];const service={provider:'gemini',isInitialized:true};for(const name of names)service[name]=async(...args)=>{legacy.push({name,args});return {response:'legacy answer',metadata:{}}};const answer=async(payload,options={})=>{calls.push({payload,options});if(gate)await gate.promise;options.onDelta?.('CURRENT_DELTA');return {text:payload.image?'Zephyr launch code':'Material answer [source citation]. General knowledge: further explanation.',requestId:'qa-request'}};attachMaterialsSession(service,{materials:m,managedSession:{answerScoped:answer,status:()=>({authenticated:true})},getAIMode:()=>mode,answerDirect:answer});const invoke=name=>name.includes('Image')?service[name](image,'image/png','general',[{role:'assistant',content:'PRIOR_HISTORY_382'}],null,d=>deltas.push(d)):service[name]('Zephyr launch code','general',[{role:'assistant',content:'PRIOR_HISTORY_382'}],null,d=>deltas.push(d));return {service,legacy,calls,deltas,invoke};}
for(const mode of ['direct','managed'])for(const name of names)test(`${mode} ${name}: active context routed once with real source metadata and original history`,async t=>{const {m}=await fixture(t),h=harness(m,{mode});const result=await h.invoke(name);assert.equal(h.legacy.length,0,'active material may not fall through legacy retries');const final=h.calls.at(-1);assert.ok(final.payload.materialContext,'separate source envelope required');assert.equal(final.payload.materialContext.sessionId,m.status().id);assert.ok(final.payload.materialContext.sources.some(s=>s.page===1&&/MARIGOLD-629/.test(s.text)));assert.equal(JSON.stringify(final.payload).split('PRIOR_HISTORY_382').length-1,1,'history duplicated or lost');assert.doesNotMatch(final.payload.text,/MARIGOLD-629/,'material merged into question');assert.ok(result.metadata.sources.length,'citation metadata lost');if(!name.includes('Image'))assert.equal(h.calls.length,1);});
for(const name of names)test(`${name}: preparing materials preserve legacy method and send no material context`,async t=>{const {m}=await fixture(t,{active:false}),h=harness(m);const r=await h.invoke(name);assert.equal(r.response,'legacy answer');assert.equal(h.legacy.length,1);assert.equal(h.calls.length,0)});
for(const mode of ['direct','managed'])for(const action of ['owner','end','remove','expire'])test(`${mode} text stream: ${action} suppresses late delta/final with no fallback`,async t=>{const f=await fixture(t),gate=deferred(),h=harness(f.m,{mode,gate});const pending=h.invoke('processTextWithSkillStream');const captured=pending.then(v=>({value:v}),error=>({error}));await tick();assert.equal(h.calls.length,1);await invalidate(f,action);gate.resolve();const result=await captured;assert.deepEqual(h.deltas,[]);assert.ok(result.error||!result.value?.response,'stale final answer escaped');assert.equal(h.legacy.length,0);assert.equal(h.calls.length,1)});
for(const action of ['owner','end','remove','expire'])test(`image question extraction: ${action} prevents second provider stage`,async t=>{const f=await fixture(t),gate=deferred(),h=harness(f.m,{gate});const pending=h.invoke('processImageWithSkillStream').catch(e=>e);await tick();assert.equal(h.calls.length,1);assert.equal(h.calls[0].payload.materialContext.sessionId,f.m.status().id,'first image stage also needs session retention marker');await invalidate(f,action);gate.resolve();await pending;assert.equal(h.calls.length,1,'late visual query triggered second paid request');assert.deepEqual(h.deltas,[]);assert.equal(h.legacy.length,0)});
