'use strict';
// Independent behavior checks execute complete production WindowManager and ExamLayout.
// Electron windows, displays, shortcut registration and disk are controlled boundaries.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),{EventEmitter}=require('events');
if (!process.argv[2] || !process.argv[3]) { console.error('Usage: node attached-navbar.cjs PROJECT_ROOT EVIDENCE_DIR'); process.exit(2); }
const ROOT=path.resolve(process.argv[2]), OUT=path.resolve(process.argv[3]);fs.mkdirSync(OUT,{recursive:true});
const records=[];const hash=require('crypto').createHash;const sourceHashes={};
function fixture({saved,conflict,area={x:0,y:0,width:1600,height:1000}}={}) {
 let timers=[],windows=[],shortcuts=new Map(),writes=[],errors=[],displays=[{id:1,workArea:area,scaleFactor:1}];
 const later=(f,ms,...args)=>{let t=setTimeout(()=>f(...args),ms);t.unref();timers.push(t);return t;};
 class W extends EventEmitter {
  constructor(o){super();this.options=o;this.id=windows.length+1;this.visible=!!o.show;this.bounds={x:0,y:0,width:o.width,height:o.height};this.movable=o.movable!==false;this.resizable=o.resizable!==false;this.webContents=new EventEmitter();Object.assign(this.webContents,{send:(n,d)=>{this.events.push([n,d]);},isDestroyed:()=>false,setWindowOpenHandler(){},getURL:()=>this.file||''});this.events=[];windows.push(this);}
  static getAllWindows(){return windows.filter(w=>!w.destroyed)}
  async loadFile(f){this.file=f;this.webContents.emit('did-finish-load');}
  isDestroyed(){return !!this.destroyed} isVisible(){return this.visible} isFocused(){return false} isMinimized(){return false}
  showInactive(){if(!this.visible){this.visible=true;this.emit('show')}} show(){this.showInactive()} hide(){if(this.visible){this.visible=false;this.emit('hide')}}
  destroy(){this.visible=false;this.destroyed=true;this.emit('closed')} focus(){this.focused=(this.focused||0)+1}
  getBounds(){return {...this.bounds}} getPosition(){return [this.bounds.x,this.bounds.y]} getSize(){return [this.bounds.width,this.bounds.height]} getContentSize(){return this.getSize()}
  setBounds(b){Object.assign(this.bounds,b);this.emit('move');this.emit('resize')} setPosition(x,y){this.setBounds({x,y})} setSize(width,height){this.setBounds({width,height})} setContentSize(w,h){this.setSize(w,h)}
  setMinimumSize(...v){this.min=v} setMaximumSize(...v){this.max=v} setMovable(v){this.movable=v} setResizable(v){this.resizable=v}
  setAlwaysOnTop(v){this.topmost=v} isAlwaysOnTop(){return this.topmost} setVisibleOnAllWorkspaces(){} setIgnoreMouseEvents(){} setSkipTaskbar(){} setContentProtection(){} setTitle(){} moveTop(){} setFocusable(){}
 }
 const screen=Object.assign(new EventEmitter(),{getAllDisplays:()=>displays,getPrimaryDisplay:()=>displays[0],getDisplayMatching:()=>displays[0],getDisplayNearestPoint:()=>displays[0],getCursorScreenPoint:()=>({x:100,y:100})});
 const electron={BrowserWindow:W,screen,app:{getPath:()=>OUT,getAppPath:()=>ROOT},globalShortcut:{register:(k,f)=>{if(k===conflict)return false;shortcuts.set(k,f);return true},unregister:k=>shortcuts.delete(k),isRegistered:k=>shortcuts.has(k)}};
 const log={debug(){},info(){},warn(){},error:(...x)=>errors.push(x)};
 const disk={...fs,readFileSync:()=>{if(saved)return JSON.stringify(saved);throw Object.assign(Error('missing'),{code:'ENOENT'})},mkdirSync(){},writeFileSync:(p,x)=>writes.push(x),renameSync(){}};
 function load(rel){const file=path.join(ROOT,rel),src=fs.readFileSync(file,'utf8');sourceHashes[rel]=hash('sha256').update(src).digest('hex');const ctx={module:{exports:{}},__dirname:path.dirname(file),console,Buffer,process:{platform:'win32',pid:123,env:{},argv:[]},setTimeout:later,clearTimeout,setInterval:(f,ms)=>later(f,ms),clearInterval,require:n=>n==='electron'?electron:n.includes('core/logger')?{createServiceLogger:()=>log}:n.includes('core/config')?{get:k=>k==='window.webPreferences'?{}:undefined}:n==='node:fs'||n==='fs'?disk:n==='./exam-layout'?load('src/managers/exam-layout.js'):require(n)};vm.runInNewContext(src,ctx,{filename:file});return ctx.module.exports;}
 const m=load('src/managers/window.manager.js');m.initializeExamLayout({enabled:true});
 return {m,shortcuts,writes,errors,screen,windows,async boot(){await m.initializeWindows();},get main(){return m.getWindow('main')},get chat(){return m.getWindow('chat')},display(a){displays=[{id:2,workArea:a,scaleFactor:1.5}];m.examLayout.fit();},cleanup(){m.examLayout.dispose();for(const t of timers)clearTimeout(t)}};
}
async function run(name,fn,opts){let f;try{f=fixture(opts);await f.boot();await fn(f);records.push({name,pass:true});}catch(e){records.push({name,pass:false,error:e.stack});}finally{f?.cleanup()}console.log(records.at(-1).pass?'PASS':'FAIL',name)}
const eq=(a,b,msg)=>assert.equal(a,b,msg), rect=w=>({...w.getBounds()}), shape=f=>[f.main.isVisible(),f.chat.isVisible()];
(async()=>{
 await run('existing chat starts locked and hidden content persists',f=>{eq(f.chat.movable,false);eq(f.chat.resizable,false);const wc=f.chat.webContents;f.m.hideChatWindow();f.m.showChatWindow();eq(f.chat.webContents,wc);eq(f.chat.isVisible(),true)});
 await run('R1 startup toolbar only',f=>{assert.deepEqual(shape(f),[true,false]);eq(f.main.getBounds().width,400);eq(f.main.getBounds().height,34)});
 await run('R2 Chat action independent and hidden summon',f=>{f.m.switchToWindow('chat');assert.deepEqual(shape(f),[true,true]);f.m.switchToWindow('chat');assert.deepEqual(shape(f),[true,false]);f.m.hideAllWindowsExcept([]);f.m.switchToWindow('chat');assert.deepEqual(shape(f),[true,true])});
 await run('R3 V restores collapsed and expanded core only',f=>{f.m.toggleVisibility();f.m.toggleVisibility();assert.deepEqual(shape(f),[true,false]);f.m.showChatWindow();f.m.getWindow('settings').showInactive();f.m.toggleVisibility();f.m.toggleVisibility();assert.deepEqual(shape(f),[true,true]);eq(f.m.getWindow('settings').isVisible(),false)});
 await run('R4 both native pointer policies and resize interception',f=>{for(const w of [f.main,f.chat]){eq(w.movable,false);eq(w.resizable,false);for(const event of ['will-move','will-resize']){let prevented=false,b=rect(w);w.emit(event,{preventDefault(){prevented=true}},{x:900,y:900,width:900,height:900});eq(prevented,true);assert.deepEqual(rect(w),b)}}});
 await run('R4 collapsed movement survives hidden chat loading',f=>{f.chat.webContents.emit('did-start-loading');let b=rect(f.main);assert.equal(f.shortcuts.size,4);f.shortcuts.get('Ctrl+Shift+Left')();eq(f.main.getBounds().x,b.x-20);eq(f.chat.isVisible(),false)});
 await run('R4 expanded group moves and stale callback cannot act',f=>{f.m.showChatWindow();let a=rect(f.main),b=rect(f.chat),step=f.shortcuts.get('Ctrl+Shift+Left');assert.equal(typeof step,'function');step();eq(f.main.getBounds().x,a.x-20);eq(f.chat.getBounds().x,b.x-20);eq(f.chat.getBounds().y,f.main.getBounds().y+42);f.m.hideAllWindowsExcept([]);a=rect(f.main);step();assert.deepEqual(rect(f.main),a)});
 await run('R8 opening near bottom shifts pair and collapse keeps anchor',f=>{for(let i=0;i<60;i++)f.shortcuts.get('Ctrl+Shift+Down')?.();let y=f.main.getBounds().y;f.m.showChatWindow();let a=rect(f.main),b=rect(f.chat);assert(a.y<y);eq(b.y,a.y+42);assert(b.y+b.height<=984);f.m.hideChatWindow();eq(f.main.getBounds().y,a.y)});
 await run('R8 version1 position migrates chat to toolbar anchor',f=>{let a=rect(f.main);eq(a.x,100);eq(a.y,158);eq(f.m.examLayout.preferences.version,2)}, {saved:{version:1,modifier:'Ctrl+Shift',displayId:1,positions:{1:{x:100,y:200}}}});
 await run('R8 monitor removal refits combined group',f=>{f.m.showChatWindow();f.display({x:-800,y:0,width:800,height:700});for(const w of [f.main,f.chat]){const b=rect(w);assert(b.x>=-800&&b.x+b.width<=0&&b.y>=0&&b.y+b.height<=700)}eq(f.chat.getBounds().y,f.main.getBounds().y+42)});
 await run('R8 tiny display keeps reachable toolbar',f=>{eq(f.main.isVisible(),true);const b=rect(f.main);assert(b.x>=0&&b.y>=0&&b.width<=290&&b.height<=180)}, {area:{x:0,y:0,width:290,height:180}});
 await run('R10 collapse invalidates late reveal epoch',f=>{f.m.showChatWindow();let epoch=f.m.getVisibilityHideEpoch(),hide=f.m.chatHideVersion;f.m.hideChatWindow();assert(f.m.chatHideVersion>hide);eq(f.m.shouldRevealAnswerSince(epoch),false);assert.deepEqual(shape(f),[true,false])});
 await run('R11 shortcut conflict rolls back and toolbar remains visible',f=>{eq(f.shortcuts.size,0);eq(f.main.isVisible(),true);eq(f.m.examLayout.state().movement,'unavailable');assert(f.m.examLayout.state().error)}, {conflict:'Ctrl+Shift+Up'});
 await run('R4 geometry freeze drops movement and restores later',f=>{const step=f.shortcuts.get('Ctrl+Shift+Left'),b=rect(f.main);f.m.geometryFrozen=true;step?.();assert.deepEqual(rect(f.main),b);f.m.geometryFrozen=false;f.m.examLayout.sync();f.shortcuts.get('Ctrl+Shift+Left')();eq(f.main.getBounds().x,b.x-20)});
 await run('R9 menu content size bounded and movement collapses',f=>{f.m.showChatWindow();const a=rect(f.main),b=rect(f.chat);f.m.examLayout.resizeToolbarContent(400,300,f.m.examLayout.state().menuRevision);assert(f.main.getBounds().height>=200);eq(f.chat.getBounds().y,b.y);f.shortcuts.get('Ctrl+Shift+Left')();eq(f.main.getBounds().height,34);eq(f.chat.getBounds().x,f.main.getBounds().x);assert(f.main.events.some(e=>e[0]==='toolbar-menu-close'))});
 await run('R8 normal geometry round trip preserved',f=>{f.m.examLayout.setEnabled(false);f.main.setBounds({x:90,y:110,width:490,height:35});f.chat.setBounds({x:230,y:240,width:510,height:650});const a=rect(f.main),b=rect(f.chat);f.m.examLayout.setEnabled(true);f.m.examLayout.setEnabled(false);assert.deepEqual(rect(f.main),a);assert.deepEqual(rect(f.chat),b);eq(f.main.movable,true);eq(f.chat.resizable,true)});
 await run('R10 delayed voice acquisition honors later collapse',f=>{f.m.pendingVoiceHideVersion=f.m.chatHideVersion;f.m.hideChatWindow();f.m.handleRecordingStarted();assert.deepEqual(shape(f),[true,false]);eq(f.m.isRecording,true);assert(f.main.events.some(e=>e[0]==='recording-started'))});
 await run('R10 ordinary voice acquisition opens chat',f=>{f.m.pendingVoiceHideVersion=f.m.chatHideVersion;f.m.handleRecordingStarted();assert.deepEqual(shape(f),[true,true])});
 await run('R9 stale expanded resize after movement stays compact',f=>{f.m.showChatWindow();const capturedRevision=f.m.examLayout.state().menuRevision;f.m.examLayout.resizeToolbarContent(400,300,f.m.examLayout.state().menuRevision);f.shortcuts.get('Ctrl+Shift+Left')();eq(f.main.getBounds().height,34);f.m.examLayout.resizeToolbarContent(400,300,capturedRevision);eq(f.main.getBounds().height,34,'late content size must not revive dismissed menu')});
 fs.writeFileSync(path.join(OUT,'boundary-results.json'),JSON.stringify({source:ROOT,sourceHashes,scope:'Real production manager/layout; Electron and disk fixtures. Not native input qualification.',records},null,2));process.exitCode=records.some(r=>!r.pass)?1:0;
})();
