'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{performance}=require('node:perf_hooks');
const PROJECT=process.env.MATERIALS_PROJECT||path.resolve(__dirname,'../../..'),ROOT=path.join(__dirname,'results'),DECKS=path.join(ROOT,'decks');fs.mkdirSync(ROOT,{recursive:true});
const {MaterialsManager}=require(path.join(PROJECT,'src/materials'));const profile=fs.mkdtempSync(path.join(ROOT,'profile-'));let peak=process.memoryUsage().rss;const initial=peak,sampler=setInterval(()=>peak=Math.max(peak,process.memoryUsage().rss),20);const report={node:process.version,platform:process.platform,sourceBytes:0,batches:[],limits:'Representative 10-deck workload, not a worst-case archive or guaranteed memory cap. RSS includes main process and worker threads; 20ms sampling may miss shorter peaks.'};
const m=new MaterialsManager({userDataPath:profile,safeStorage:{isEncryptionAvailable:()=>false},owner:'qa-workload'});const started=performance.now();
(async()=>{try{
 const paths=Array.from({length:10},(_,i)=>path.join(DECKS,`workshop-${String(i+1).padStart(2,'0')}.pptx`));report.sourceBytes=paths.reduce((n,p)=>n+fs.statSync(p).size,0);
 for(let batch=0;batch<2;batch++){const time=performance.now();await m.importFiles(paths.slice(batch*5,batch*5+5));const docs=m.status().documents.filter(d=>!d.error&&d.pages);assert.equal(docs.length,(batch+1)*5);assert.equal(docs.reduce((n,d)=>n+d.pages,0),(batch+1)*300);report.batches.push({acceptedFiles:docs.length,totalPages:docs.reduce((n,d)=>n+d.pages,0),importElapsedMs:Math.round(performance.now()-time)});peak=Math.max(peak,process.memoryUsage().rss)}
 await m.start({consent:true});let decodedTextBytes=0,visualPages=0;for(const doc of m.status().documents){visualPages+=doc.coverage.visualPages||0;for(let page=1;page<=doc.pages;page++){const p=await m.preview(doc.id,page);decodedTextBytes+=Buffer.byteLength(p.text||'')+Buffer.byteLength(p.notes||'')}}
 const query='What reserve threshold and approval codename are specified in HELIOSDECK10SLIDE55?',retrievalStart=performance.now(),ctx=m.retrieve(query,{maxChars:4000});assert.ok(ctx.sources.some(s=>s.name==='workshop-10.pptx'&&s.page===55&&s.text.includes('9473 liters')&&s.text.includes('COBALT-MEADOW')),'late deck fact must cite real deck10 slide55');const contextChars=ctx.sources.reduce((n,s)=>n+s.text.length,0);assert.ok(contextChars<=4000);assert.equal(m.status().documents.filter(d=>!d.error&&d.pages).length,10);
 Object.assign(report,{success:true,acceptedFiles:10,totalPages:600,decodedTextBytes,visualPages,contextChars,retrievalElapsedMs:Math.round((performance.now()-retrievalStart)*100)/100,citedFact:ctx.sources.filter(s=>s.text.includes('HELIOSDECK10SLIDE55')).map(({name,page,kind})=>({name,page,kind}))});
 }catch(error){report.success=false;report.error=error.stack}
 finally{peak=Math.max(peak,process.memoryUsage().rss);clearInterval(sampler);Object.assign(report,{elapsedMs:Math.round(performance.now()-started),initialRssBytes:initial,peakSampledRssBytes:peak,processLifetimeMaxRssKiB:process.resourceUsage().maxRSS});await m.close();fs.rmSync(profile,{recursive:true,force:true});fs.writeFileSync(path.join(ROOT,'workload.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.success?0:1}
})();
