'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const project=process.env.MATERIALS_PROJECT||'/mnt/c/users/endeg/Desktop/NoCatch-session-materials',archive=path.resolve(process.argv[2]||'');assert.ok(process.argv[2],'usage: node verify-archive.cjs <app.asar>');
const asar=require(require.resolve('@electron/asar',{paths:[project]}));
const files=asar.listPackage(archive).map(n=>n.replaceAll('\\','/').replace(/^\//,''));
const required=['materials.html','preload.js','main.js','src/ui/materials.js','src/ui/materials.css','src/ui/materials-links.js','src/materials/index.js','src/materials/extractor.js','src/materials/extract-worker.js','src/materials/context.js','src/services/materials-routing.js','src/services/materials-direct-answer.js','node_modules/yauzl/package.json','node_modules/fast-xml-parser/package.json','node_modules/pdfjs-dist/legacy/build/pdf.mjs','node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs','node_modules/@napi-rs/canvas/index.js','node_modules/@napi-rs/canvas-win32-x64-msvc/skia.win32-x64-msvc.node'];
const report={archive,archiveBytes:fs.statSync(archive).size,required:[],limitations:['Archive inventory is not runtime verification; also execute full-main.cjs with MATERIALS_PROJECT pointing at this app.asar in native Electron']};
for(const name of required){assert.ok(files.includes(name),'missing archive entry: '+name);const info=asar.statFile(archive,name);let bytes;if(info.unpacked){const p=path.join(archive+'.unpacked',name);bytes=fs.readFileSync(p);assert.equal(bytes.length,info.size);if(info.integrity?.hash)assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),info.integrity.hash)}else bytes=asar.extractFile(archive,name);assert.ok(bytes.length,'empty archive entry: '+name);if(name.endsWith('.node'))assert.equal(info.unpacked,true,'native canvas binary must ship unpacked');report.required.push({name,bytes:bytes.length,unpacked:!!info.unpacked,sha256:crypto.createHash('sha256').update(bytes).digest('hex')})}
const root=path.join(__dirname,'results');fs.mkdirSync(root,{recursive:true});report.success=true;fs.writeFileSync(path.join(root,'archive-materials.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({success:true,entries:report.required.length,archive}));
